01:12:30 AM: DEBUG [logger_base.py:13] Message from the level debug
01:12:30 AM: INFO [logger_base.py:14] Message from the level info
01:12:30 AM: WARNING [logger_base.py:15] Message from the level warning
01:12:30 AM: ERROR [logger_base.py:16] Message from the level error
01:12:30 AM: CRITICAL [logger_base.py:17] Message from the level critical
02:14:46 AM: DEBUG [person.py:51] 
                Id Person: 15, Name: pepe
                Last name: hdz, Email: mi@hotmail.com
               
02:20:55 AM: DEBUG [person.py:52] 
                Id Person: 15, Name: pepe
                Last name: hdz, Email: mi@hotmail.com
               
02:22:50 AM: DEBUG [person.py:52] 
                Id Person: 15, Name: pepe
                Last name: hdz, Email: mi@hotmail.com
               
02:22:50 AM: DEBUG [person.py:55] 
                Id Person: None, Name: pepe
                Last name: hdz, Email: mi@hotmail.com
               
02:22:50 AM: DEBUG [person.py:58] 
                Id Person: 1, Name: None
                Last name: None, Email: None
               
02:57:59 AM: DEBUG [connection.py:25] Connection successful :<connection object at 0x7f3ef1e71040; dsn: 'user=linuxdev password=xxx dbname=test_db_udemy host=localhost port=5432', closed: 0>
02:59:22 AM: DEBUG [connection.py:25] Connection successful :<connection object at 0x7fedb658e040; dsn: 'user=linuxdev password=xxx dbname=test_db_udemy host=localhost port=5432', closed: 0>
02:59:22 AM: DEBUG [connection.py:38] the cursor has opened correctly : <cursor object at 0x7fedb775a040; closed: 0> 
